# The INVOKER: Hierarchical queue consumption (Private > High > Medium > Low)
# Usage: PRIVATE_QUEUE=worker_gpu1 docker-compose up -d
# Or edit .env file to set PRIVATE_QUEUE=worker_yourname

version: '3.8'

services:
  worker:
    build:
      context: ./app
    container_name: wyolo_invoker_${WORKER_HOSTNAME:-default}
    image: wisrovi/train_service:worker_invoker_v1.0.0
    restart: always
    deploy:
      resources:
        reservations:
          memory: 100M
    environment:
      - PRIVATE_QUEUE=${WORKER_HOST:-default}
    env_file:
      - config/control_host.env
      - config/user.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/wyolo/request:/wyolo/worker/request
      - /home/wyolo/train_service_results:/home/wyolo/train_service_results
    networks:
      - train_service
    labels:
      - "autoheal=true"
      - "com.centurylinklabs.watchtower.enable=true"
    # Re-enable healthcheck after the first successful build
    # healthcheck:
    #   test: [ "CMD", "celery", "-A", "worker_gpu", "inspect", "ping", "-d", "celery@worker_${WORKER_NAME:-default}" ]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    command: >
      celery -A worker_gpu worker -E -Q ${WORKER_HOST:-default},gpus_high,gpus_medium,gpus_low  --loglevel=info --concurrency=1 --prefetch-multiplier=1  -Ofair --max-tasks-per-child=1 --max-memory-per-child=250000

  dashboard:
    build: ./UI/simple_dashboard
    container_name: dashboard_${WORKER_NAME:-default}
    image: wisrovi/train_service:worker_invoker_dashboard_v1.0.0
    restart: always
    ports:
      - "8082:8000"
    env_file:
      - config/control_host.env
      - config/user.env
    environment:
      - OPTUNA_DB_URL=postgresql://postgres:postgres@192.168.10.252:23436/wyoloservice
    # volumes:
    #   - ./app/config.yaml:/app/invoker/config.yaml
    command: uvicorn dashboard_app:app --host 0.0.0.0 --port 8000
    networks:
      - train_service

  # wpipe-scanner:
  #   image: wisrovi/train_service:worker_executor_v1.0.0
  #   restart: always
  #   volumes:
  #     - /wyolo/worker/events:/wyolo/worker/events
  #   command: bash -c 'python -m wpipe.dashboard --db /wyolo/worker/events/wtrain.db --port 8036'
  #   ports:
  #     - "8082:8036"
  #   networks:
  #     - train_service

  gradio_launcher:
    build: ./UI/gradio_launcher
    image: wisrovi/train_service:worker_invoker_gradio_v1.0.0
    container_name: gradio_launcher_${WORKER_NAME:-default}
    restart: always
    ports:
      - "8083:7860"
    env_file:
      - config/control_host.env
      - config/user.env
    volumes:
      - /home/wyolo/train_service_results:/results
    command: python gradio_app.py
networks:
  train_service:
    name: train_service
    external: true
