version: '3.8'

services:
  
  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal_${WORKER_NAME}
    restart: always
    environment:
      - AUTOHEAL_INTERVAL=10
      - CURL_TIMEOUT=30
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - train_service

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower_${WORKER_NAME}
    restart: always
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_SCHEDULE=0 0 0,2,4,6,8,10,12,14,16,18,20,22 * * *
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - train_service

networks:
  train_service:
    name: train_service
    external: true