# Worker Config - Total Control
redis:
  host: "192.168.10.252"  # IP del Servidor Central (CONTROL_HOST)
  port: 23437
  db: 0

optuna:
  # IP y Puerto del servidor central (Postgres distribuido)
  storage_url: "postgresql://postgres:postgres@<IP>:23436/wyoloservice"

celery:
  concurrency: 1        # Cuántos contenedores executor lanzar a la vez (ej: 1 por GPU)
  loglevel: "INFO"
  queue: "gpus"

worker:
  executor_image: "wisrovi/train_service:worker_executor_v1.0.0"
  host_temp_dir: "/tmp" # Carpeta en el HOST para volúmenes efímeros
  cpu_limit_pct: 0.85   # % máximo de cores a usar (0.0 a 1.0)
  mem_limit_pct: 0.60   # % máximo de RAM a usar (0.0 a 1.0)
  results_dir: "/home/wyolo/train_service_results"
