# mypy: ignore-errors
# pylint: disable=all
# ruff: noqa
"""LLM Analyzer State Module.

This module provides the LlmAnalizer class for post-training analysis.

The report is now generated by the EXECUTOR, which writes an ``llm.md``
file into the shared results directory. This state simply reads that file
and exposes it through the Celery task state so the UI / MCP can render it
without the invoker calling OpenCode itself.
"""

from pathlib import Path
from typing import Any, Dict

RESULTS_DIR = "/home/wyolo/train_service_results"
LLM_MD_NAME = "extras/llm/llm.md"


class LlmAnalizer:
    """State class for reading the executor-generated LLM training report."""

    NAME: str = "LLMAnalizer"
    VERSION: str = "2.0.0"

    def __init__(self, config: dict[str, Any]):
        """Initialize LLM Analyzer with configuration.

        Args:
            config: Worker configuration dictionary.
        """
        self.config = config

    def __call__(self, training_config: dict[str, Any]) -> dict[str, Any]:
        """Read the ``llm.md`` report written by the executor.

        Args:
            training_config: Training configuration and results.

        Returns:
            Dict[str, Any]: Analysis results.
        """
        print(f"--- [STATE:{self.NAME}] Reading executor llm.md report... ---")
        report_file = Path(RESULTS_DIR) / LLM_MD_NAME

        try:
            if not report_file.exists():
                raise FileNotFoundError(f"llm.md not found at {report_file}")

            report = report_file.read_text(encoding="utf-8").strip()
            if not report:
                raise ValueError("llm.md is empty")

            return {
                "status": "success",
                "llm_report": report,
            }
        except Exception as exc:
            print(f"LLM Analyzer failed: {exc}")
            return {
                "status": "failed",
                "llm_report": "",
                "error": str(exc),
            }
