version: '3.8'

services:
  gradio_launcher:
    build:
      context: .
      dockerfile: Dockerfile
    image: wisrovi/train_service:worker_invoker_gradio_v1.0.0
    restart: always
    ports:
      - "7860:7860"
    env_file:
      - ./config/control_host.env
      - ./config/user.env
    volumes:
      - /home/wyolo/train_service_results:/results
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
